#!/bin/bash

# dumps schema of table(s) from a MySQL database.
# TODO: cope with other database engines as needed.

usage() {
    echo >&2 "usage: $0 [-d database] tabname ..."
    exit 1
}

: ${DBNAME:=mysql}
while getopts :d: ch; do
    case "$ch" in
      d) DBNAME="$OPTARG";;
      *) usage;;
    esac
done

mysql -D $DBNAME -B -t <<END
  select $*;
END

