#!/bin/bash

# performs a select on a MySQL database.
# TODO: cope with other database engines as needed.

dbname=tod_dev
lflag=

usage() {
    echo >&2 "usage: $0 [-d database] -l ['likepattern'] | tabname ...
where   -d  select database (default $dbname)
        -l  list tables (optionally like pattern)"

    exit 1
}

while getopts :d:l ch; do
    case "$ch" in
      d) dbname="$OPTARG";;
      l) lflag=1;;
      *) usage;;
    esac
done
shift $((OPTIND-1))

if [[ -z "$lflag" ]]; then
  [[ $# -eq 0 ]] && usage

  for i in "$@"; do
    echo "describe $i;"
  done
elif [[ $# -eq 0 ]]; then
    echo "show tables;"
else
    echo "show tables like '$*';"
fi | mysql -D $dbname -B -t
