#!/bin/bash
myname="${0##*/}"

# performs a table schema dump on a MySQL database.
# TODO: cope with other database engines as needed.

: ${DBNAME:=mysql}
lflag=
Bflag=-B
tflag=-t

usage() {
    [[ $# -gt 0 ]] && echo >&2 "$myname:" "$@"

    echo >&2 "usage: $myname [-d database] -l ['likepattern'] | tabname ...
where   -d  select database (default \$DBNAME:=mysql)
        -l  list tables (optionally like pattern)"

    exit 1
}


# why do BSD-inspired getopts like to be so complicated but hate +opt ???
while [[ "X$1" = X[-+]* ]]; do
    val="${1:0:1}"
    opt="${1:1}"
    shift

    while [[ -n "$opt" ]]; do
        ch="${opt:0:1}"
        opt="${opt:1}"

        # following opts consume a mandatory arg: -d
        arg=
        if [[ "X$val$ch" == X-[d] ]]; then
            if [[ -z "$opt" ]]; then
                arg="$1"
                shift
            else
                arg="$opt"
                opt=
            fi
        fi

        case "$val$ch" in
          -d) DBNAME="$arg" ;;
          -l) lflag=1 ;;
          +B) Bflag= ;;
          +t) tflag= ;;
          *)  usage "unknown option $val$ch" ;;
        esac
    done
done


if [[ -z "$lflag" ]]; then
    [[ $# -eq 0 ]] && usage

    for i in "$@"; do
        echo "describe $i;"
    done
elif [[ $# -eq 0 ]]; then
    echo "show tables;"
else
    echo "show tables like '%$*%';"
fi | mysql -D $DBNAME $Bflag $tflag

