#!/bin/bash

EXPECTED_ARGS=3
E_BADARGS=65

if [ $# -ne $EXPECTED_ARGS ]
then
  echo "Usage: `basename $0` DUMP_PATH DUMP_FILE DEST_DB"
  echo "Restore a database from a dump file in gz format."
  exit $E_BADARGS
fi


DUMP_PATH=$1
DUMP_FILE=$2
DB=$3

DUMP_PATH_FILE=$DUMP_PATH/$DUMP_FILE

gzip -cd $DUMP_PATH_FILE | mysql $DB
rcs=(${PIPESTATUS[*]})
rc_zip=${rcs[0]}
rc_db=${rcs[1]}
if [[ $rc_zip != 0 ]]; then
  echo "Unable to unzip from dump file $DUMP_PATH_FILE."
  exit $rc_zip
fi
if [[ $rc_db != 0 ]]; then
  echo "Unable to execute mysql for $DB."
  exit $rc_db
fi

exit 0

