#!/bin/ksh

rdev() {
    tmux                                               \
        new-session                                 \; \
        split-window -h                             \; \
        send-keys app Enter                         \; \
        send-keys cd Space app/views Enter          \; \
        split-window                                \; \
        send-keys app Enter                         \; \
        send-keys cd Space app/helpers Enter        \; \
        select-pane -L                              \; \
        send-keys app Enter                         \; \
        send-keys cd Space app/models Enter         \; \
        split-window                                \; \
        send-keys app Enter                         \; \
        send-keys cd Space app/controllers Enter    \; \
        select-pane -U
}

