#!/bin/ksh

rserv() {
    tmux new-session \;                                     \
         split-window -h \;                                 \
         send-keys app Enter \;                             \
         send-keys bundle Space exec Space                  \
                   script/server Space --debugger Enter \;  \
         select-pane -L \;                                  \
         send-keys app Enter \;                             \
         send-keys bey Space script/console Enter
}

