#!/bin/ksh


rvert() {
    # crude but fair
    dive=
    [[ "X$1" == X--app ]] && dive='send-keys APP Enter ;'

    tmux                   \
        new-session     \; \
        split-window -h \; \
        $dive              \
        select-pane -L  \; \
        $dive
}

