#!/bin/ksh


rvert() {

    tmux                        \
        new-session         \;  \
        split-window -h     \;  \
        send-keys app Enter \;  \
        select-pane -L      \;  \
        send-keys app Enter \;
}

