#! /bin/sh
#
# /etc/init.d/informix
#

### BEGIN INIT INFO
# Provides:          Informix
# Required-Start:    
# Should-Start:      $time
# Required-Stop:     
# Should-Stop:       
# Default-Start:     2 3 5
# Default-Stop:      0 1 6
# Short-Description: Informix Dynamic Server
# Description:       Start Informix Dynamic Server
### END INIT INFO

service=suzyq

## exit 0

. /etc/rc.status

rc_reset        # First reset status of this service

PROFILE=/etc/informix/profile.d/$service


if [[ ! -f $PROFILE ]]; then
    echo "Cannot find $PROFILE"
    exit 1
fi

. $PROFILE
cd $INFORMIXDIR

case "$1" in
    start)
	echo -n "Starting Informix engine $service "
	oninit
	rc_status -v ;;         # Remember status and be verbose

    stop)
	echo -n "Shutting down Informix engine $service "
        onmode -yuk
	rc_status -v ;;         # Remember status and be verbose

    status)
        onstat - > /dev/null
        stat=$?
        # map the indicator exit code from onstat into something rc* can use
        ( if [[ $stat == 255 ]]; then exit 7; else exit 0; fi )
        rc_status -v
        ;;

    try-restart)
        # Stop the service and if this succeeds (i.e. the 
        # service was running before), start it again.
        $0 status > /dev/null && $0 restart
        rc_status ;;            # Remember status and be quiet

    restart)
        # Stop the service and regardless of whether it was running or not, start it again.
        $0 stop
        $0 start
        rc_status ;;            # Remember status and be quiet

    *)
	echo "Usage: $0 {start|stop|status|try-restart|restart}"
	exit 1
	;;
esac
rc_exit

