#!/bin/bash

if [[ $# -ne 5 ]]; then
    cat >&2 <<++
Usage: `basename $0` SRC_DB DEST_DB EMAIL_OFF PASSWORD_RESET SET_EMAIL_TO_EXAMPLE_COM

Copy a database from Sydney production server to OVERWRITE another one in
the Sydney customer uat server and optionally turn off email reminder,
reset admin password and update emails to @example.com.

Note: valid values for the options are 'yes' and 'no'.
++

  exit 1
fi

SRC_DB="$1"
DEST_DB="$2"
EMAIL_OFF="$3"
PASSWORD_RESET="$4"
EXAMPLE_COM="$5"
SRC_HOST=web1.aws.tod.net.au
DEST_HOST=custuatweb1-internal

## backup_cust "$DEST_DB"
ssh -A "ubuntu@$SRC_HOST" /home/ubuntu/bin/copy_db_to "$SRC_DB" "$DEST_HOST" "$DEST_DB" "$EMAIL_OFF" "$PASSWORD_RESET" "$EXAMPLE_COM"

